Question 1 (30 Points)

A sample of 30 respondents was interviewed using mall intercept interviewing. The respondents were asked to indicate their degree of agreement with the following statements using a seven-point scale (1 = strongly disagree, 7 = strongly agree).

•	V1 = It is important to buy a toothpaste that prevents cavities

•	V2 = I like a toothpaste that gives a shiny teeth

•	V3 = A toothpaste should strengthen your gums teeth

•	V4 = I prefer a toothpaste that freshens breath

•	V5 = Prevention of tooth decay is not an important benefit offered by a toothpaste

•	V6 = The most important consideration in buying a toothpaste is attractive teeth

By using the variables,

(1) How many factors is extracted from data for principal component analysis?

(2) What is the total percentage of variance explained by these principal components?

(3)Which variables are included in the same factors ? How can you name these factors?

You can find the data at

https://raw.githubusercontent.com/ogut77/DataScience/main/data/Toothpaste.csv

In [15]:
import pandas as pd
tp=pd.read_csv("https://raw.githubusercontent.com/ogut77/DataScience/main/data/Toothpaste.csv")
print(tp)
from sklearn.preprocessing import StandardScaler
X= StandardScaler().fit_transform(tp)
X=pd.DataFrame(X)
X.columns=tp.columns
X


     V1   V2   V3   V4   V5   V6
0   7.0  3.0  6.0  4.0  2.0  4.0
1   1.0  3.0  2.0  4.0  5.0  4.0
2   6.0  2.0  7.0  4.0  1.0  3.0
3   4.0  5.0  4.0  6.0  6.0  5.0
4   1.0  2.0  2.0  3.0  2.0  2.0
5   6.0  3.0  6.0  4.0  4.0  4.0
6   5.0  3.0  6.0  3.0  1.0  3.0
7   6.0  4.0  7.0  4.0  6.0  4.0
8   3.0  4.0  2.0  3.0  7.0  3.0
9   2.0  6.0  2.0  6.0  2.0  6.0
10  6.0  4.0  7.0  3.0  5.0  3.0
11  2.0  3.0  1.0  4.0  1.0  4.0
12  7.0  2.0  6.0  4.0  3.0  3.0
13  4.0  6.0  4.0  5.0  6.0  6.0
14  1.0  3.0  2.0  2.0  3.0  4.0
15  6.0  4.0  6.0  3.0  3.0  4.0
16  5.0  3.0  6.0  3.0  1.0  4.0
17  7.0  3.0  7.0  4.0  6.0  4.0
18  2.0  4.0  3.0  3.0  6.0  3.0
19  3.0  5.0  3.0  6.0  4.0  6.0
20  1.0  3.0  2.0  3.0  5.0  3.0
21  5.0  4.0  5.0  4.0  2.0  4.0
22  2.0  2.0  1.0  5.0  4.0  4.0
23  4.0  6.0  4.0  6.0  4.0  7.0
24  6.0  5.0  4.0  2.0  1.0  4.0
25  3.0  5.0  4.0  6.0  4.0  7.0
26  4.0  4.0  7.0  2.0  2.0  5.0
27  3.0  7.0  2.0  6.0  4.0  3.0
28  4.0  6.0  3.0  7.0  2.0  7.0
29  2.0  3

V1        V2        V3        V4        V5        V6
0   1.574088 -0.666514  0.939490 -0.074057 -0.857015 -0.121806
1  -1.505649 -0.666514 -1.038383 -0.074057  0.717095 -0.121806
2   1.060798 -1.407086  1.433958 -0.074057 -1.381719 -0.852645
3   0.034219  0.814629 -0.049447  1.407086  1.241798  0.609032
4  -1.505649 -1.407086 -1.038383 -0.814629 -0.857015 -1.583483
5   1.060798 -0.666514  0.939490 -0.074057  0.192391 -0.121806
6   0.547509 -0.666514  0.939490 -0.814629 -1.381719 -0.852645
7   1.060798  0.074057  1.433958 -0.074057  1.241798 -0.121806
8  -0.479070  0.074057 -1.038383 -0.814629  1.766501 -0.852645
9  -0.992360  1.555200 -1.038383  1.407086 -0.857015  1.339870
10  1.060798  0.074057  1.433958 -0.814629  0.717095 -0.852645
11 -0.992360 -0.666514 -1.532851 -0.074057 -1.381719 -0.121806
12  1.574088 -1.407086  0.939490 -0.074057 -0.332312 -0.852645
13  0.034219  1.555200 -0.049447  0.666514  1.241798  1.339870
14 -1.505649 -0.666514 -1.038383 -1.555200 -0.332312 -0.121806
15  1.060798  0.074057  0.939490 -0.814629 -0.332312 -0.121806
16  0.547509 -0.666514  0.939490 -0.814629 -1.381719 -0.121806
17  1.574088 -0.666514  1.433958 -0.074057  1.241798 -0.121806
18 -0.992360  0.074057 -0.543915 -0.814629  1.241798 -0.852645
19 -0.479070  0.814629 -0.543915  1.407086  0.192391  1.339870
20 -1.505649 -0.666514 -1.038383 -0.814629  0.717095 -0.852645
21  0.547509  0.074057  0.445021 -0.074057 -0.857015 -0.121806
22 -0.992360 -1.407086 -1.532851  0.666514  0.192391 -0.121806
23  0.034219  1.555200 -0.049447  1.407086  0.192391  2.070709
24  1.060798  0.814629 -0.049447 -1.555200 -1.381719 -0.121806
25 -0.479070  0.814629 -0.049447  1.407086  0.192391  2.070709
26  0.034219  0.074057  1.433958 -1.555200 -0.857015  0.609032
27 -0.479070  2.295771 -1.038383  1.407086  0.192391 -0.852645
28  0.034219  1.555200 -0.543915  2.147657 -0.857015  2.070709
29 -0.992360 -0.666514 -1.038383 -0.074057  1.766501 -1.583483

In [16]:
#1
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(tp)
n_factors = pca.n_components_
print("Number of extracted factors: ", n_factors)

Number of extracted factors:  6


In [17]:
#2
pca = PCA(n_components=6)
principalComponents = pca.fit_transform(X)
pca.explained_variance_ratio_

array([0.39747021, 0.30295205, 0.16145572, 0.07131525, 0.05138315,
       0.01542362])

In [18]:
#3
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(tp)
loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
loadings_tp = pd.DataFrame(loadings, columns=[f"PC{i+1}" for i in range(loadings.shape[1])], index=tp.columns)
print(loadings_tp)

         PC1       PC2       PC3       PC4       PC5       PC6
V1  1.853438 -0.433372  0.201157 -0.245687  0.338173  0.296996
V2 -0.326022 -1.122797 -0.121872  0.520118  0.470016 -0.113808
V3  1.965757 -0.218439  0.308023  0.193838 -0.299954 -0.310960
V4 -0.421173 -1.095186 -0.153159 -0.658935  0.022612 -0.226325
V5 -0.640966 -0.375526  1.787602  0.015368 -0.081897  0.056133
V6 -0.141308 -1.164885 -0.447406  0.168283 -0.517454  0.252203


PC1: V1,V3. PC2: V2,V6 . PC3: V5. PC4: V2. PC5: V2. PC6: V1,V6

Factor 1: Dentifortify (Cavity Protection & Gum Strengthening) Factor 2: Attractive teeth Factor 3: Cavities not important Factor 4: Shiny smile Factor 5: Shiny smile Factor 6: Smileguard

In [12]:
#Q2
import pandas as pd
breast_dataset=pd.read_csv('https://raw.githubusercontent.com/ogut77/DataScience/main/data/Bcancer.csv')
breast_dataset
y=breast_dataset['label']
X=breast_dataset.drop(['label'], axis = 1)
X

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

Q2) (70 points)Using breast cancer data above,

(1) split the data two : training (65%) and testing (35%)

(2) Using logistic regression model in train data, get the performance metric on test data(accuracy,recall, precision confusuion matrix)

(3)Using knn model in train data(choose k based on CV), get the performance metric on test data(accuracy,recall, precision confusuion matrix). What is the k value chosen based on k?

(4)Using naive  model in train data, get the performance metric on test data(accuracy,recall, precision confusuion matrix)

(5)Using SVM with parameter tuning(you can use optuna) in train data ,get the performance metric on test data(accuracy,recall, precision confusuion matrix)

In [7]:
#1
from sklearn.model_selection import StratifiedKFold, train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=17)

In [8]:
#2
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix
logisticReg = LogisticRegression()
logisticReg.fit(X_train, y_train)
y_pred = logisticReg.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.915
Recall: 0.9375
Precision: 0.9302325581395349
Confusion Matrix:
 [[ 63   9]
 [  8 120]]


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [9]:
#3
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
k_values = range(1, 21)
accuracies = []
for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    scores = cross_val_score(knn, X_train, y_train, cv=5, scoring='accuracy')
    accuracies.append(scores.mean())

best_k = k_values[accuracies.index(max(accuracies))]

knn = KNeighborsClassifier(n_neighbors=best_k)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("Confusion Matrix:\n", conf_matrix)
print("Best k:", best_k)

Accuracy: 0.935
Recall: 0.9609375
Precision: 0.9389312977099237
Confusion Matrix:
 [[ 64   8]
 [  5 123]]
Best k: 6


In [13]:
#4
from sklearn.naive_bayes import GaussianNB
naiveBayes = GaussianNB()
naiveBayes.fit(X_train, y_train)
y_pred = naiveBayes.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.94
Recall: 0.96875
Precision: 0.9393939393939394
Confusion Matrix:
 [[ 64   8]
 [  4 124]]


In [3]:
!pip install optuna

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 3.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.4/233.4 kB 7.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 2.8 MB/s eta 0:00:00


In [ ]:
# 5 But this code seems not working...
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
X_train2, X_val, y_train2, y_val = train_test_split(X, y, test_size=0.35, random_state=42)
def objective(trial):
  C = trial.suggest_loguniform('C', 1e-3, 1e3)
  kernel = trial.suggest_categorical('kernel', ['linear', 'poly', 'rbf', 'sigmoid'])
  degree = trial.suggest_int('degree', 2, 5)
  gamma = trial.suggest_loguniform('gamma', 1e-3, 1e3)
  model = SVC(C=C, kernel=kernel, degree=degree, gamma=gamma)
  model.fit(X_train2, y_train2)
  y_pred = model.predict(X_val)
  accuracy = accuracy_score(y_val, y_pred)
  return accuracy
import optuna as op
study = op.create_study(direction='maximize')
study.optimize(objective, n_trials=10)
print("Best C:", study.best_params['C'])
print("Best kernel:", study.best_params['kernel'])
print("Best degree:", study.best_params['degree'])
print("Best gamma:", study.best_params['gamma'])
best_model = SVC(**study.best_params)
best_model.fit(X_train, y_train)
accuracy = accuracy_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("Confusion Matrix:\n", conf_matrix)